if(EXISTS "/home/trindade/Projetos/scout++/build_release/test_filesystem[1]_tests.cmake")
  include("/home/trindade/Projetos/scout++/build_release/test_filesystem[1]_tests.cmake")
else()
  add_test(test_filesystem_NOT_BUILT test_filesystem_NOT_BUILT)
endif()
