if(EXISTS "/home/trindade/Projetos/scout++/build_release/test_xref[1]_tests.cmake")
  include("/home/trindade/Projetos/scout++/build_release/test_xref[1]_tests.cmake")
else()
  add_test(test_xref_NOT_BUILT test_xref_NOT_BUILT)
endif()
